apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - image:  github.com/vagababov/prime-server
          ports:
            - name: http1
              containerPort: 8080

  traffic:
  - tag: current
    revisionName: prime-api-pos
    percent: 50
  - tag: candidate
    revisionName: prime-api-neg
    percent: 50
  - tag: latest
    latestRevision: true
    percent: 0

