apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    metadata:
      name: prime-api-neg
    spec:
      containerConcurrency: 15
      containers:
        - image:  github.com/vagababov/prime-server
          args: ["--negate", "true"]
  traffic:
  - revisionName: prime-api-pos
    percent: 60
  - revisionName: prime-api-neg
    percent: 40
  - tag: latest
    latestRevision: true
    percent: 0

