apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    metadata:
      name: prime-api-pos
    spec:
      containerConcurrency: 15
      containers:
        - image:  github.com/vagababov/prime-server

