apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    metadata:
      name: prime-api-pos
    spec:
      containers:
        - image:  github.com/vagababov/prime-server
          ports:
            - name: http1
              containerPort: 8080

